### ISSUE TITLE
Actividad de Etica y Deontologia

### ISSUE THREAD

**Issue by 412432-Castelli-Nicolas-Francisco** [FMonforte/TST-PROYECTO-INTEGRADOR#5]
Busquen y lean sobre algunos casos recientes de violaciones de seguridad.

Aspectos básicos/situación

Las violaciones de seguridad ocurren cuando personas o aplicaciones intentan obtener acceso no autorizado a datos, aplicaciones, servicios o dispositivos. Durante estas violaciones de seguridad, los atacantes, sean infiltrados o no, intentan obtener información que podrían usar para conseguir beneficios financieros u otras ventajas. En este laboratorio explorarán algunas violaciones de seguridad para determinar qué fue tomado, qué ataques se usaron y qué pueden hacer para protegerse.

Busquen tres vulnerabilidades de seguridad que hayan ocurrido en argentina y respondan por cada una lo siguiente, puedes también realizar un cuadro comparativo.

a)Fecha del incidente

b)Organización afectada

c) Cuantas victimas hubo? ¿Que fue tomado?

d)¿Que tipo de ataque se utilizó?
e) Link al articulo

**Comment by FMonforte** [comment]
Se sube el pdf solicitado de Deontología
[Casos de Violaciones de Seguridad en Argentina.pdf](https://github.com/FMonforte/TST-PROYECTO-INTEGRADOR/files/11714967/Casos.de.Violaciones.de.Seguridad.en.Argentina.pdf)
